<?php
       $config_values=ConfigValues::model();
       $block_view=$config_values->get_ralation_values('2');
       $sort_select=$config_values->get_ralation_values('4');
       $block_view=Util::com_search_item(array(''=>'请选择模块视图'),$block_view);
       $sort_select=Util::com_search_item(array(''=>'请选择文档排序'),$sort_select);
       $pattern=Util::com_search_item(array(''=>'请选择模型'),CV::$pattern);
       $this->widget('SearchItems', array( 
          'model_name'=>'Blocks', 
          'user_operate'=>array(
              array(
               'name'=>'增加模块',
               'value'=>$this->createUrl("add",array()),
              ),
          ),
          //搜索的内容字段
      'search_datas'=>array(
          'pattern'=>array(
						'name'=>'模型',
						'type'=>'select',
						'select'=>$page_params['pattern'],
						'value'=>$pattern,
						'htmlOptions'=>array(),
			 	 ),
         'name'=>array(
               'name'=>'名称',
               'type'=>'text',//搜索框的类型
               'select'=>$page_params['name'],
               'value'=>'',
               'htmlOptions'=>array(),
           ),
			 	'identification'=>array(
						'name'=>'标识',
						'type'=>'text',
						'select'=>$page_params['identification'],
						'value'=>'',
						'htmlOptions'=>array(),
			 	 ),
			 	 'view'=>array(
						'name'=>'模块视图',
						'type'=>'select',
						'select'=>$page_params['view'],
						'value'=>$block_view,
						'htmlOptions'=>array(),
			 	 ),
			 	 'sort'=>array(
						'name'=>'文档排序',
						'type'=>'select',
						'select'=>$page_params['sort'],
						'value'=>$sort_select,
						'htmlOptions'=>array(),
			 	 ),
      ), 
     'dataprovider'=>$dataProvider,
          //列表显示的字段
      'attributes'=>array(
        array(
         'name'=>'id',
         'type'=>'raw',//字段的属性 参考yii
         'value'=>'$data->id',//如果为空则以$data->id为值 如果有值则 已$data->func()填充
        ),
        
       array(
				'name'=>'pattern',
				'type'=>'raw',
				'value'=>'$data->show_attribute("pattern")',
			 ),
			 array(
				'name'=>'name',
				'type'=>'raw',
				'value'=>'$data->name',
			 ),
    	 array(
         'name'=>'identification',
         'type'=>'raw',
         'value'=>'$data->show_attribute("identification")',
     	), 
			array(
				'name'=>'view',
				'type'=>'raw',
				'value'=>'$data->show_attribute("view")',
			),
			array(
				'name'=>'tlen',
				'type'=>'raw',
				'value'=>'$data->show_attribute("tlen")',
			),
			array(
				'name'=>'dott',
				'type'=>'raw',
				'value'=>'$data->show_attribute("dott")',
			),
			array(
				'name'=>'dlen',
				'type'=>'raw',
				'value'=>'$data->show_attribute("dlen")',
			),
			array(
				'name'=>'size',
				'type'=>'raw',
				'value'=>'$data->show_attribute("size")',
			),
			array(
				'name'=>'archive_ids',
				'type'=>'raw',
				'value'=>'$data->show_attribute("archive_ids")',
			),
			array(
				'name'=>'channel',
				'type'=>'raw',
				'value'=>'$data->show_attribute("channel")',
			),
			array(
				'name'=>'category',
				'type'=>'raw',
				'value'=>'$data->show_attribute("category")',
			),
			array(
				'name'=>'attr',
				'type'=>'raw',
				'value'=>'$data->show_attribute("attr")',
			),
			array(
				'name'=>'sort',
				'type'=>'raw',
				'value'=>'$data->show_attribute("sort")',
			),
			array(
				'name'=>'sort_type',
				'type'=>'raw',
				'value'=>'$data->show_attribute("sort_type")',
			),
		  array(
				'name'=>'limit',
				'type'=>'raw',
				'value'=>'$data->show_attribute("limit")',
			),
			array(
				'name'=>'cache',
				'type'=>'raw',
				'value'=>'$data->show_attribute("cache")',
			),
    	array(
         'name'=>'操作',
         'type'=>'raw',
          'value'=>'$data->get_operate()',
      ),    
     ),
      //批量操作按钮
      'operates'=>array(
         array(
               'name'=>'删除所有',
               'value'=>'javascript:batch_operate(\''.$this->createUrl("delete",array()).'\');'
             ),
          ),
         //是否需要全选列
       'checked_all'=>true,
        //是否使用ajax翻页
        'ajax'=>false,    
    ));
?>