<?php
	   $config_value_type=Util::com_search_item(array(''=>'变量类型'),CV::$config_value_type);
       $this->widget('SearchItems', array( 
          'model_name'=>'ConfigValues', 
          'user_operate'=>array(
              array(
               'name'=>'增加变量',
               'value'=>$this->createUrl("add",array()),
              ),
          ),
          //搜索的内容字段
      'search_datas'=>array(
         'name'=>array(
               'name'=>'变量名称',
               'type'=>'text',//搜索框的类型
               'select'=>$page_params['name'],
               'value'=>'',
               'htmlOptions'=>array(),
           ),  
			 'type'=>array(
					'name'=>'变量类型',
					'type'=>'select',
					'select'=>$page_params['type'],
					'value'=>$config_value_type,
					'htmlOptions'=>array(),
			 ),
      ), 
     'dataprovider'=>$dataProvider, 
          //列表显示的字段
      'attributes'=>array(
        array(
         'name'=>'id',
         'type'=>'raw',//字段的属性 参考yii
         'value'=>'$data->id',//如果为空则以$data->id为值 如果有值则 已$data->func()填充
        ),
			 array(
				'name'=>'type',
				'type'=>'raw',
				'value'=>'$data->show_attribute("type")',
			 ),
      array(
         'name'=>'name',
         'type'=>'raw',
         'value'=>'$data->show_attribute("name")',
    	 ),
			 array(
				'name'=>'value',
				'type'=>'raw',
				'value'=>'$data->value',
			), 
    	 array(
         'name'=>'extern_value',
         'type'=>'raw',
         'value'=>'$data->show_attribute("extern_value")',
     	),
			array(
				'name'=>'sort',
				'type'=>'raw',
				'value'=>'$data->sort',
			),
    	array(
         'name'=>'操作',
         'type'=>'raw',
          'value'=>'$data->get_operate()',
      ),   
     ),
          //批量操作按钮
          'operates'=>array(
             array(
               'name'=>'删除所有',
               'value'=>'javascript:batch_operate(\''.$this->createUrl("delete",array()).'\');'
             ),
          ),
          //是否需要全选列
          'checked_all'=>true,
          //是否使用ajax翻页
          'ajax'=>false,    
       ));
?>