<?php
       $channels=Channels::model();
       $channels_select=$channels->get_channel_select('0',"","downloads");
       $channels_select=Util::com_search_item(array(''=>'选择栏目'),$channels_select);
       $channel_category=ChannelCategory::model();
       $category_select=$channel_category->get_select("0");
       $category_select=Util::com_search_item(array(''=>'选择分类'),$category_select);
       $config_values=ConfigValues::model();
       $archive_att=$config_values->get_select_values('1');
       $archive_att=Util::com_search_item(array(''=>'文章属性'),$archive_att);
       $archives_status=CV::$archives_status;
       array_pop($archives_status);
       $status=Util::com_search_item(array(''=>'审核状况'),$archives_status);
       if($page_params['status']=='3'){
        $operate=array(
             array(
               'name'=>'彻底删除所有',
               'value'=>'javascript:batch_operate(\''.$this->createUrl("delete",array()).'\');'
             ),
        );
      }else{
      	 $operate=array(
             array(
               'name'=>'批量删除',
               'value'=>'javascript:batch_operate(\''.$this->createUrl("status",array('status'=>'3')).'\');'
             ),
             
             array(
               'name'=>'批量审核',
               'value'=>'javascript:batch_operate(\''.$this->createUrl("status",array('status'=>'2')).'\');'
            ),
        );
      }
       $this->widget('SearchItems', array( 
          'model_name'=>'Downloads', 
          'user_operate'=>array(
              array(
               'name'=>'返回到下载管理',
               'value'=>$this->createUrl("index",array('channel_id'=>$page_params['channel_id'],'status'=>$page_params['status'])),
             ),
             array(
				       'name'=>'新增下载',
				       'value'=>$this->createUrl("add",array('channel_id'=>$page_params['channel_id']))
				     ),
				     array(
				       'name'=>'审核下载',
				       'value'=>$this->createUrl("index",array('status'=>'1','channel_id'=>$page_params['channel_id']))
				     ),
				      array(
				       'name'=>'栏目管理',
				       'value'=>$this->createUrl("channels/index",array())
				     ),
				      array(
				       'name'=>'下载回收站',
				       'value'=>$this->createUrl("index",array('status'=>'3','channel_id'=>$page_params['channel_id']))
				     ),
          ),
      //搜索的内容字段
     'search_datas'=>array(
       'keyword'=>array(
               'name'=>'关键字',
               'type'=>'text',//搜索框的类型
               'select'=>$page_params['keyword'],
               'value'=>'',
               'htmlOptions'=>array(),
        ),
        'channel_id'=>array(
               'name'=>'栏目',
               'type'=>'select',//搜索框的类型
               'select'=>$page_params['channel_id'],
               'value'=>$channels_select,
               'htmlOptions'=>array(),
        ),
        'category_id'=>array(
               'name'=>'分类',
               'type'=>'select',//搜索框的类型
               'select'=>$page_params['category_id'],
               'value'=>$category_select,
               'htmlOptions'=>array(),
        ),
         'attr'=>array(
               'name'=>'属性',
               'type'=>'select',//搜索框的类型
               'select'=>$page_params['attr'],
               'value'=>$archive_att,
               'htmlOptions'=>array(),
        ),
         'status'=>array(
               'name'=>'审核状态',
               'type'=>'select',//搜索框的类型
               'select'=>$page_params['status'],
               'value'=>$status,
               'htmlOptions'=>array(),
        ),
      ), 
     'dataprovider'=>$dataProvider, 
          //列表显示的字段
      'attributes'=>array(
        array(
         'name'=>'id',
         'type'=>'raw',//字段的属性 参考yii
         'value'=>'$data->id',//如果为空则以$data->id为值 如果有值则 已$data->func()填充
        ),
      array(
         'name'=>'channel_id',
         'type'=>'raw',
         'value'=>'$data->show_attribute("channel_id")',
    	 ),
			  
    	 array(
         'name'=>'category_id',
         'type'=>'raw',
         'value'=>'$data->show_attribute("category_id")',
     	),
			array(
			  'name'=>'title',
			  'type'=>'raw',
			  'value'=>'$data->show_attribute("title")',
			),
			array(
			  'name'=>'下载地址',
			  'type'=>'raw',
			  'value'=>'$data->show_download_address()',
			),
			array(
				'name'=>'update_time',
				'type'=>'raw',
				'value'=>'$data->show_attribute("update_time")',
			),
			
			array(
				'name'=>'downloads_times',
				'type'=>'raw',
				'value'=>'$data->show_attribute("downloads_times")',
			),
			array(
				'name'=>'vots',
				'type'=>'raw',
				'value'=>'$data->show_attribute("vots")',
			),
			
			array(
				'name'=>'create_id',
				'type'=>'raw',
				'value'=>'$data->show_attribute("create_id")',
			),
			
			array(
				'name'=>'status',
				'type'=>'raw',
				'value'=>'$data->show_attribute("status")',
			),
    	array(
         'name'=>'操作',
         'type'=>'raw',
          'value'=>'$data->get_operate()',
      ),
          
     ),
          //批量操作按钮
        'operates'=>$operate,
          //是否需要全选列
          'checked_all'=>true,
          //是否使用ajax翻页
          'ajax'=>false,    
       ));
?>